# Generated by Django 5.2.4 on 2025-07-07 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='session_key',
            new_name='session_id',
        ),
    ]
