# Generated by Django 5.2.4 on 2025-07-07 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_session_key_chat_session_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='session_id',
            new_name='session',
        ),
    ]
