# Generated by Django 5.2.4 on 2025-07-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_session_id_chat_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcp_path', models.CharField(max_length=500)),
                ('ollama_model', models.CharField(max_length=100)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
